### ISSUE TITLE
i used 3.4.0, but the itemview have no recycled 

### ISSUE THREAD

**Issue by qq2748** [drakeet/MultiType#275] opened 2019-05-25 08:38 UTC
![image](https://user-images.githubusercontent.com/9549979/58366926-707b3000-7f0b-11e9-8ee4-dfe2eac24ba4.png)

**Comment by drakeet** [comment] 2019-07-02 13:47
Since there is no reproduction and description, and it seems that this is not a problem with MultiType, I am going to close this issue.

**Closed as completed by drakeet** 2019-07-02 13:47 UTC
